#!/usr/bin/env bash

#install nginx server
apt-get update
apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

#tests server configuration
sudo nginx -t
sudo service nginx restart
sudo service nginx reload
