#!/usr/bin/env bash

#install nginx server
apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default

/etc/init.d/nginx restart

echo "Nginx installed and configured."
