#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

#package list update
sudo apt-get -y update

#package installation
sudo apt-get -y install software-properties-common

#HAProxy repository addition and installation
sudo add-apt repository -y ppa:vbernat/haproxy-2.0
sudo app-get -y update
sudo apt-get -y install haproxy

#Configure HAProxy
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 231137-web-01 100.26.210.32 check
    server 231137-web-02 100.26.157.149 check
"

#HAProxy configuration added to HAProxy.cfg
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg

#HAProxy service start
sudo service haproxy start
