#!/usr/bin/env bash
#Script to generate MySQL dump and a generate a
#compressed archive of it
mysqldump -u root -p"$1" --opt --all-databases > backup.sql

date=$(date +"%d-%m-%Y")
tar -czvf "$date.tar.gz" backup.sql
