#!/usr/bin/env bash
#A  Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

idx=1

while [ $idx -le 10 ]
do
	if [ $idx -eq 9 ]
	then
	     echo "Best School"
	     echo "Hi"
	else
	     echo "Best School"
	fi
	idx=$((idx+1))
done
