#!/usr/bin/env bash
#Let’s install the ufw firewall and setup a few rules on web-01
#Exceptions for port 22, 443 and 80.
sudo apt-get update
sudo apt-get install ufw
sudo ufw default deny incoming
sudo uwf default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sud ufw status
