#!/usr/bin/env bash
#script that runs command under another user
if [ $# -eq 1 ]; then
    # Use sudo to run the 'whoami' command as the specified user
    sudo -u $1 whoami
else
    echo "Usage: $0 <username>"
    exit 1
fi
