#!/usr/bin/env bash
#Bash script that configures the container to fit

#Set the user that Nginx will run as
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
#Ensure Nginx listens on all active IPs on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
#Giving owner permissions r+w to config file
chmod 644 /etc/nginx/nginx.conf
#Kill apache2 process
pkill apache2
#Restart nginx
sudo -u nginx service nginx restart
